steps:
    - key: ci
      label: ":bazel: ci"
      env:
          BAZELRC: .buildkite/.bazelrc
      secrets:
          - BUILDBUDDY_API_KEY
      command: |
          bazel run //:gazelle -- -mode=diff
          bazel run //:format -- check
          bazel build //...
          bazel test //...
          bazel run --run_in_cwd @multitool//tools/typos
          bazel run //tools/filename_linter:main
      agents:
          queue: default

    - label: ":rocket: deploy playground"
      trigger: "playground-deploy"
      branches: "main"
      depends_on: ci
      async: true
      build:
          branch: "${BUILDKITE_BRANCH}"
          commit: "${BUILDKITE_COMMIT}"
