steps:
    - label: ":bazel: ci"
      env:
          BAZELRC: .buildkite/.bazelrc
      command: |
          bazel mod deps --lockfile_mode=error
          bazel run //:gazelle -- -mode=diff
          bazel run //:format -- check
          bazel build //...
          bazel test //...
          bazel run --run_in_cwd @multitool//tools/typos
          bazel run //tools/filename_linter:main
      agents:
          queue: default
